name: Build Kivy APK

on:
  push:
    branches: ["master"]  # твоя ветка master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git build-essential \
            openjdk-17-jdk unzip zip libffi-dev libssl-dev liblzma-dev zlib1g-dev
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/requirements = python3/requirements = python3,kivy/g' buildozer.spec
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4  # ⚡ здесь обновили с v3 на v4
        with:
          name: apk
          path: bin/*.apk